version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    image: ws_2_db_image
    container_name: usersdb2
  standalone:
    build:
      context: ./standalone
    image: ws_2_standalone_image
    container_name: standalone2
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 8000:8000
